# ===================================================================
#          Default Configuration for TransfQMix Experiment
# ===================================================================

# --- Top-level settings ---
experiment_name: "transfqmix_long_explore_v1"
seed: 42
use_cuda: true

# ===================================================================
#                       Environment Configuration
# ===================================================================
environment:
  episode_data_directory: "marl_framework/episode_data"
  # Set to null to train on all episodes in the directory
  specific_episode_file: "ep_SIM_all_features_R64_C64_S500_ID0000.npz" 

  # --- Grid and Agent Setup ---
  GRID_SIZE_R: 64
  GRID_SIZE_C: 64
  NUM_AGENTS: 3
  NUM_HEADINGS: 8

  # --- Observation and Communication ---
  OBSERVATION_RADIUS_AGENTS: 10
  COMMUNICATION_RADIUS_CELLS: 15
  DIRECT_SENSING_MODE: "surrounding_cells"

  # --- Feature and Normalization ---
  CNN_OUTPUT_FEATURE_DIM: 64
  MAX_EXPECTED_CURRENT_MPS: 2.0

  # --- Reward Structure ---
  REWARD_SCALING_FACTOR: 100.0
  PENALTY_PER_STEP: 0 
  COLLISION_PENALTY: -1.0 # Smaller penalty for collision vs. boundary
  BOUNDARY_VIOLATION_PENALTY: -2.0 # Penalty for hitting a wall

  # --- Episode Control ---
  MAX_STEPS_PER_EPISODE: 400
  FALLBACK_ENV_TIME_STEP_HOURS: 0.1
  # NEW: Optional termination for boundary violation
  TERMINATE_ON_BOUNDARY_VIOLATION: false # Set to true to revert to old, harsher behavior

  # --- State Representation for Mixer ---
  INCLUDE_GLOBAL_BELIEF_IN_STATE: true
  INCLUDE_GROUND_TRUTH_IN_STATE: false # Disabled for now to simplify state space
  GLOBAL_BELIEF_POOLED_DIM: 8

# ===================================================================
#                    Agent Neural Network Configuration
# ===================================================================
agent_nn:
  BELIEF_MAP_PROCESSOR: "maxpool"
  BELIEF_MAP_POOL_DIM: 8
  CNN_OUTPUT_FEATURE_DIM: 64
  AGENT_TRANSFORMER_EMBED_DIM: 64
  AGENT_TRANSFORMER_NUM_HEADS: 4
  AGENT_TRANSFORMER_NUM_BLOCKS: 2
  AGENT_TRANSFORMER_FFN_DIM_MULTIPLIER: 4
  AGENT_TRANSFORMER_DROPOUT_RATE: 0.1

# ===================================================================
#                    Mixer Neural Network Configuration
# ===================================================================
mixer_nn:
  MIXER_TRANSFORMER_EMBED_DIM: 64
  MIXER_TRANSFORMER_NUM_HEADS: 4
  MIXER_TRANSFORMER_NUM_BLOCKS: 2
  MIXER_TRANSFORMER_FFN_DIM_MULTIPLIER: 4
  MIXER_TRANSFORMER_DROPOUT_RATE: 0.1
  MIXER_MLP_HIDDEN_DIM: 64

# ===================================================================
#                         Training Configuration
# ===================================================================
training:
  num_training_episodes: 100000 # Increased for longer training
  learning_starts_episodes: 100 # Increased to get better initial random data
  batch_size: 64
  replay_buffer_capacity: 40000

  # --- Optimizer and Learning Control ---
  learning_rate: 0.0001 # DECREASED
  gamma: 0.99
  tau: 0.005
  grad_norm_clip: 10.0

  # --- Exploration (Epsilon-Greedy) ---
  epsilon_start: 1.0
  epsilon_finish: 0.05
  epsilon_anneal_time: 5000000 # INCREASED SIGNIFICANTLY

  # --- Network Updates and Evaluation ---
  target_update_interval_episodes: 20 # Slower updates
  evaluation_interval_episodes: 200
  num_evaluation_episodes: 5
  save_model_interval_episodes: 500

# ===================================================================
#                  Logging and Visualization Configuration
# ===================================================================
logging:
  log_dir: "logs"
  tb_log_dir: "runs"
  model_save_dir: "saved_models"
  visualization_gif_output_dir: "visualizations"
  log_level: "INFO"

  # --- GIF Generation ---
  visualization_enabled: true
  visualization_interval_eval_episodes: 5
  visualization_duration_per_frame_ms: 300