# --- MaxPool Belief Processor Experiment ---
experiment_name: "TransfQMix_BeliefMaxPool"
seed: 42 # For reproducibility

# --- Environment Parameters ---
environment:
  episode_data_directory: "marl_framework/episode_data"
  specific_episode_file: null
  GRID_SIZE_R: 64
  GRID_SIZE_C: 64
  NUM_AGENTS: 3
  NUM_HEADINGS: 8
  OBSERVATION_RADIUS_AGENTS: 10
  COMMUNICATION_RADIUS_CELLS: 5
  DIRECT_SENSING_MODE: "surrounding_cells"
  MAX_STEPS_PER_EPISODE: 300
  MAX_EXPECTED_CURRENT_MPS: 2.0
  FALLBACK_ENV_TIME_STEP_HOURS: 0.1
  INCLUDE_GLOBAL_BELIEF_IN_STATE: true
  GLOBAL_BELIEF_POOLED_DIM: 8

# --- Reward Parameters ---
rewards:
  REWARD_SCALING_FACTOR: 100.0
  PENALTY_PER_STEP: 0

# --- Agent Network Parameters (Shared by all agents) ---
agent_nn:
  BELIEF_MAP_PROCESSOR: "maxpool" # Use the simpler MaxPooler
  MAXPOOL_DIM: 8 # The output dimension of the adaptive max pool (8x8)
  CNN_OUTPUT_FEATURE_DIM: 128 # This is now the output dim of the FC layer after pooling
  AGENT_TRANSFORMER_EMBED_DIM: 64
  AGENT_TRANSFORMER_NUM_HEADS: 4
  AGENT_TRANSFORMER_NUM_BLOCKS: 2
  AGENT_TRANSFORMER_FFN_DIM_MULTIPLIER: 2
  AGENT_TRANSFORMER_DROPOUT_RATE: 0.1

# --- Mixer Network Parameters ---
mixer_nn:
  MIXER_TRANSFORMER_EMBED_DIM: 64
  MIXER_TRANSFORMER_NUM_HEADS: 4
  MIXER_TRANSFORMER_NUM_BLOCKS: 2
  MIXER_TRANSFORMER_FFN_DIM_MULTIPLIER: 2
  MIXER_TRANSFORMER_DROPOUT_RATE: 0.1
  MIXER_MLP_HIDDEN_DIM: 64

# --- Training Parameters ---
training:
  num_training_episodes: 50000
  batch_size: 32
  replay_buffer_capacity: 50000
  learning_rate: 0.0003
  gamma: 0.99
  tau: 0.005
  epsilon_start: 1.0
  epsilon_finish: 0.05
  epsilon_anneal_time: 5000
  target_update_interval_episodes: 10
  grad_norm_clip: 10.0
  learning_starts_episodes: 100
  evaluation_interval_episodes: 50
  num_evaluation_episodes: 5
  save_model_interval_episodes: 100

# --- CUDA ---
use_cuda: true

# --- Logging and Visualization ---
logging:
  log_dir: "marl_framework/logs"
  log_level: "INFO"
  tb_log_dir: "marl_framework/runs"
  model_save_dir: "marl_framework/saved_models"
  visualization_enabled: false
  visualization_interval_eval_episodes: 1
  visualization_gif_output_dir: "marl_framework/episode_gifs"
  visualization_duration_per_frame_ms: 150